version: 0.0
os: linux
files:
  - source: /
    destination: /backend-repo
    overwrite: true
hooks:
  # BeforeInstall:
  #   - location: scripts/beforeInstall.sh
  #     timeout: 300
  #     runas: root
  # AfterInstall:
  #   - location: scripts/afterInstall.sh
  #     timeout: 300
  #     runas: root
  # ApplicationStop:
  #   - location: scripts/applicationStop.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 3000
      runas: root
  